### ISSUE TITLE
Multiple Default Refresh Listed

### ISSUE THREAD

**Issue by JonathanDLee24** [mmd123/squid-cache-dynamic_refresh-list#11]
There are multiples of the default.
![1661180437542-same](https://user-images.githubusercontent.com/111817527/186036978-9b5cdc09-7ed1-421a-b24d-cea4fa21b560.png)
![1661180472883-same2](https://user-images.githubusercontent.com/111817527/186037030-93b2ca9d-0022-41aa-976c-a908aedd02af.png)

I noticed that it should only use one of them. Maybe if it added #360 mins fresh 1 day store
**#180 mins fresh 30 days store
#30 mins fresh 1 day store**

and note above
**#only choose one**

If you run all three of them, it slows the cache down.

![1661180665750-same3](https://user-images.githubusercontent.com/111817527/186037121-84491b7e-c6f8-4306-910e-910cc32b7c9f.png)
(Image: Reference Squid Website Why choose one)

**Comment by JonathanDLee24** [comment]
https://forum.netgate.com/topic/172137/any-recommendations-this-custom-refresh_pattern/7?_=1661210555422

Ref: Request made by Netgate Forum Members to post issue here

**Comment by mmd123** [comment]
huh....good catch, I completely missed that on my end admittedly.  though it has been a while since I combed through these myself, yea, that's a good catch, and should not be there multiple times.  given that in all honesty, ageekhere has been far more helpful on this than I have been, I will temporarily comment out the catchall section, awaiting his final suggested input/fix for this, but for now, I will go that route on my side. @ageekhere depending on your suggestion, feel absolutely free to change my fix for now.

**Comment by ageekhere** [comment]
https://github.com/mmd123/squid-cache-dynamic_refresh-list/pull/12

**Comment by mmd123** [comment]
changes / edits commited, going to close this issue now that said, thank you once again @ageekhere and thank you for pointing this out @JonathanDLee24

**Comment by JonathanDLee24** [comment]
No problem,

refresh_pattern . 0 20% 4320

Should also be the last item as it is the default cache all.



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ageekhere** [comment]
@mmd123 @JonathanDLee24 Ah yes refresh_pattern . 0 20% 4320 should be last on the list, @mmd123 for now just move refresh_pattern . 0 20% 4320 to the bottom.

**Comment by mmd123** [comment]
done
