### ISSUE TITLE
Steam/epic games Cache

### ISSUE THREAD

**Issue by ageekhere** [mmd123/squid-cache-dynamic_refresh-list#3]
Maybe this can help in caching steam and epic games.

http://opensourcelan.com/blog/2016/07/01/steam-cdn

**Comment by saki22** [comment]
Not trying to be rude who is this

**Comment by ageekhere** [comment]
I created the original post on improving refresh patterns in pfsense 
https://forum.netgate.com/topic/99613/improve-custom-refresh-pattern?_=1618217773077 

Been also looking at https://lancache.net/ and wonder if that could be useful

**Comment by saki22** [comment]
Oh okay

**Comment by saki22** [comment]
I hope I was not being rude

**Comment by mmd123** [comment]
honestly I use both, one two punch, lancache-monolithic for steam caching, and squid for anything else I can manage to get cached.  steamcache/lancache is designed specifically for use with game cdns like blizzard/battle.net origin, epic games, and steam specifically, so it just works, and has its own implementation of ssl decryption for the systems that use https for content delivery, and in my experience it just flat out works, so that's definitely the easier route for game caching.

**Comment by ageekhere** [comment]
I wonder if lancache can be made into a pfsense package, or would it be better running on a server?

**Comment by mmd123** [comment]
honestly for me its running in a vm on vmware esxi, and can not easily be ported into pfsense given that they opted to make it a docker container image, and that was the only form I could get to work after spending far too long trying....also when you consider it has to run its own sni-proxy to decrypt/intercept the ssl requests...no, this is not something that could easily be ported into pfsense as far as I am aware, especially not given this github is to try and use with squid, given that would be two different systems that would possibly try and intercept ssl traffic, if you opt to do squid the way I am doing squid.  better to try and run two separate systems IMO

**Comment by ageekhere** [comment]
Hey, with the fixes i did squid steam cache is now working! can anyone else confirm?

**Comment by mmd123** [comment]
> Hey, with the fixes I did squid steam cache is now working! can anyone else confirm?

refresh my memory real fast, are you using SSL interception or not, I had disabled my squid package for a good while now due to having other issues that were becoming far too hard to fix when using squid, so I'll test it and find out, but I need to ask due to not remembering, are you using SSL interception or just transparent mode?

**Comment by ageekhere** [comment]
I am not using SSL interception. It looks like steam is no longer sending download data via ssl.

**Comment by ageekhere** [comment]
After testing it seems content from http://steam.cdn.on.net/ is cacheable, will add a new refresh pattern for that address.
